### ISSUE TITLE
incorrect fsf address in COPYING

### ISSUE THREAD

**Issue by Chingyat** [vdudouyt/stm8flash#104]
Hi. 
I am trying to create an RPM package for stm8flash and rpmlint is complaining about incorrect fsf address.

```
stm8flash.x86_64: E: incorrect-fsf-address /usr/share/doc/stm8flash/COPYING
```

https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address sais I should report this here.

---

According to http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt, the current address is

```
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
```

Please change it.

**Comment by spth** [comment]
Done.

Philipp
