### ISSUE TITLE
stm8flash not run

### ISSUE THREAD

**Issue by Qitas** [vdudouyt/stm8flash#124]
./stm8flash: symbol lookup error: ./stm8flash: undefined symbol: libusb_set_option

**Comment by spth** [comment]
Did you compile stm8flash yourself?

The error message looks as if the stm8flash you use was compiled with libusb 1.0.22 or newer, but you are trying to run it using an older libusb version older than 1.0.22.

**Comment by spth** [comment]
Closing, since no further information was provided. Assuming this is the libusb 1.0.22 verion issue.

**Comment by jxltom** [comment]
Same issue here in ubuntu 16 with ```apt install libusb-1.0.0-dev```
