### ISSUE TITLE
Won't compile under Raspbian stretch.

### ISSUE THREAD

**Issue by jtannenba** [vdudouyt/stm8flash#130]
Can't fina a libusb.h file under Raspian Stretch.  What am I missing?  Is there a binary for Raspbian?  I'm just trying 'Make stm8flash'.
Thank you.
Joe

**Comment by schneidersoft** [comment]
Old post but hey...
You need to install the required libusb dependancies.
I don't remeber what they are exactly.
try:
`sudo apt install libusb-1.0-0-dev`
or
`sudo apt install libusb-dev`
