### ISSUE TITLE
Issue with serial numbers

### ISSUE THREAD

**Issue by nitko12** [vdudouyt/stm8flash#135]
Hi,

I think you should hardcode 12 in this for loop, 

that fixed the issue I was having, 
because strlen returns length until the first 0, which isn't the true length of the serial number I presume?

https://github.com/vdudouyt/stm8flash/blob/1fe6521473dcc8615fcf77edc8e22ade6e6ccb56/main.c#L159

**Comment by spth** [comment]
I merged the fix by @schneidersoft.
