### ISSUE TITLE
not HEX file for reading procedures.

### ISSUE THREAD

**Issue by iDoka** [vdudouyt/stm8flash#14]
I can't compare [use diff] writed and readed image by reason I get same result after following command:

```
$ stm8flash -cstlinkv2 -pstm8s103 -r main.ihx
$ stm8flash -cstlinkv2 -pstm8s103 -r main.bin
```

 the same binary file as output. For burning I use HEX fileformat.

How does work option -v? Unfortunately, my verification procedure by using stm8flash always fail.

**Comment by spth** [comment]
Support for the .ihx file extension has been implemented nearly two years ago; a remaining bug in verification was fixed a month ago.

Philipp
