### ISSUE TITLE
how to reset stm8 with stm8flash (with no power down)

### ISSUE THREAD

**Issue by JiaDuo** [vdudouyt/stm8flash#140]
I don't kown how to reset the stm8 use stm8, I known when flash a program ,it will be reset auto. 
I want to reset wihtout flash .how to do that ?

thanks

**Comment by stefaandesmet2003** [comment]
there is no command line option for reset only, but write a 0 byte file will trigger a reset
./stm8flash -c stlinkv2 -p stm8s103f3 -s eeprom -b 0 -w dummy.bin

**Comment by schneidersoft** [comment]
It seems there is a need for proper independent reset control. see  also #153
