### ISSUE TITLE
eeprom+opt read/write on stm8s103?3 and stm8s105?4 is working ok

### ISSUE THREAD

**Issue by stefaandesmet2003** [vdudouyt/stm8flash#143]
just a short contribution to confirm that I tested these configurations with a ST-LINK V2 (chinese clone) and they are working correctly.
Each time I read eeprom (all zeroes), executed a program to fill eeprom with all 0xFF, another read with stm8flash -r to confirm all 0xFF, wrote back all zeroes with stm8flash -w, and verified with stm8flash -r that eeprom contains all zeroes. All OK.
I used the -s opt before to change option bytes both on S103 & S105 (bootloader, i2c, unlock), and all worked OK.
Thanks for your useful tool.

**./stm8flash -c stlinkv2 -p stm8s103?3 -s eeprom -w 103_eeprom.bin**
Determine EEPROM area
Due to its file extension (or lack thereof), "103_eeprom.bin" is considered as RAW BINARY format!
640 bytes at 0x4000... OK
Bytes written: 640

**./stm8flash -c stlinkv2 -p stm8s103?3 -s eeprom -r 103_eeprom.bin**
Determine EEPROM area
Due to its file extension (or lack thereof), "103_eeprom.bin" is considered as RAW BINARY format!
Reading 640 bytes at 0x4000... OK
Bytes received: 640

**./stm8flash -c stlinkv2 -p stm8s105?4 -s eeprom -w 105_eeprom.bin**
Determine EEPROM area
Due to its file extension (or lack thereof), "105_eeprom.bin" is considered as RAW BINARY format!
1024 bytes at 0x4000... OK
Bytes written: 1024

**./stm8flash -c stlinkv2 -p stm8s105?4 -s eeprom -r 105_eeprom.bin**

**Comment by spth** [comment]
Thanks. I updated the README.
