### ISSUE TITLE
stlinkv3 and swim reset

### ISSUE THREAD

**Issue by gabbla** [vdudouyt/stm8flash#148]
Hello,

I am trying to read the flash of an STM8L101F2P3 (`stm8l101?2` from a stm8flash point-of-view) via stlinkv3 without any success.
I built the tool with `DEBUG=1` and it always goes into error when it tries to assert the reset pin:

```
✘130 ➜ ./stm8flash -c stlinkv3 -p "stm8l101?2" -s flash -r /tmp/dummy.hex
Determine FLASH area
     GET_VERSION
STLink: v3, JTAG: v0, SWIM: v0, VID: 8304, PID: 4f37
     GET_CURRENT_MODE
        -> 01 03
     DFU EXIT
     SWIM ENTER
     SWIM READBUFSIZE
        -> 0x1800
     SWIM READ_CAP 01
        -> 00 01 00 30 00 00 00 00
     SWIM ASSERT_RESET
IO error: expected 4 bytes but 2 bytes transferred
```

also, I need to unplug the stlink before I can try again.

Any help?

Thank you,
Gab

**Comment by spth** [comment]
@gabbla: can you confirm that is is now fixed in current master?

**Comment by gabbla** [comment]
@spth I will test it tomorrow evening and I update you.

**Comment by gabbla** [comment]
@spth Ran the same test as above, it works as expected!

Gab
