### ISSUE TITLE
Eclipse IDE support

### ISSUE THREAD

**Issue by rtek1000** [vdudouyt/stm8flash#163]
Hi, I'm using Eclipse to compile STM8 through a compile.sh script that executes the Makefile.

One thing I would like to be able to see when compiling is memory usage (Flash/RAM).

I'm controlling the size of the code through the information that stm8flash returns when programming.

Would it be possible to adapt some plugin for Eclipse to recognize stm8flash in a similar way to what STM32CubeIDE does to recognize ST-Link?

Ref.: [SDCC support](https://sourceforge.net/p/sdcc/support-requests/188/)

[W1209-firmware-modified-timer_bkp1.zip](https://github.com/vdudouyt/stm8flash/files/11184774/W1209-firmware-modified-timer_bkp1.zip)

**Comment by schneidersoft** [comment]
I'm not sure I understand what you want stm8flash to do. You want it to automatically detect which model of MCU you have connected?

**Comment by lalo-uy** [comment]
Ibelive you have to look at the output of the linker.
May be add some command to the Makefile to list the segments and total memory usage.

**Comment by spth** [comment]
When using an IDE, it might make more sense to use GDB/OpenOCD instead of stm8flash. stm8flash can only do basic stuff, such as read and write the flash and other memories. GDB/OpenOCD can do on-target debugging.

**Comment by rtek1000** [comment]
> When using an IDE, it might make more sense to use GDB/OpenOCD instead of stm8flash. stm8flash can only do basic stuff, such as read and write the flash and other memories. GDB/OpenOCD can do on-target debugging.


I found these instructions, in case anyone wants to see it, it looks like a good alternative, I'll try it:

https://github.com/hbendalibraham/stm8_started

**Comment by rtek1000** [comment]
> I'm not sure I understand what you want stm8flash to do. You want it to automatically detect which model of MCU you have connected?

Now I see there is another option, I was searching the internet before I came to read the answers, and found the instructions already posted above. I was wondering about the debug options that the STM32CubeIDE has.

**Comment by rtek1000** [comment]
Thanks all
