### ISSUE TITLE
Option Bytes programming

### ISSUE THREAD

**Issue by lwojdziak** [vdudouyt/stm8flash#22]
Hello,

I'm trying to programm option bytes at stm8s003 using stlinkv2.  
There is an information about opt2 writing in compatibility table - there is no suppoprt for opt's yet.

Theoretically there is almost all what you need to run opt writing.
When I try to write at 0x4800 stm8 returned write confirmation but after reading using veryfi option there are old values.

What missing in source code to write and check opt values?
How can I modify project to run this feature?

br

**Comment by vdudouyt** [comment]
Hi,

And did you already checked for #3e04c73?

**Comment by lwojdziak** [comment]
OK, works fine.
Thanks a lot!
