### ISSUE TITLE
stm8s103 flash works with stm8flash and stlinkv2

### ISSUE THREAD

**Issue by sehellion** [vdudouyt/stm8flash#23]
Work with a flash and eeprom not tested.

**Comment by MykolaPrymak** [comment]
Flash  works. EEPROM not tested.

**Comment by spth** [comment]
Which stm8s103? STM8S103F2? STM8S103F3?

For STM8S103F3 the current README says it works, but for STM8S103F2 it is still marked as untested.

Philipp

**Comment by spth** [comment]
Closing as no further information was provided.
