### ISSUE TITLE
Change license from GPLv2 to GPLv2 or later.

### ISSUE THREAD

**Issue by spth** [vdudouyt/stm8flash#34]
The README.md states "This is a free and opensource software distributed under the terms of GNU General Public License v2."

I suggest to change the license to GPLv2 or later, i.e. change the text to ""This is a free and opensource software distributed under the terms of GNU General Public License; either version 2 of the License, or (at your option) any later version."

This would be a license change, so all authors would have to agree.

However, I think it would be good to make this change, to allow combining stm8flash with software released under later GPL versions, should the need arise. It would be quite frustrating to not be able to do some things due to license issues, even when all involved software is GPL-licensed.

Philipp

**Comment by rpavlik** [comment]
I've only made minor contributions, but please feel free to relicense my contributions as GPL2+.

**Comment by cpldcpu** [comment]
My contributions are minimal, no objection from my side.

**Comment by spth** [comment]
Done.
