### ISSUE TITLE
Cannot use STM32VLDISCOVERY Board

### ISSUE THREAD

**Issue by frank-u** [vdudouyt/stm8flash#53]
Determine FLASH area
stm8flash: stlink.c:162: stlink_send_cbw: Assertion `actual == USB_CBW_SIZE' failed.
Aborted (core dumped)

**Comment by lkord** [comment]
this tool is for STM8 targets, try OpenOCD or texane/stlink

**Comment by spth** [comment]
Closing, since STM32 is not supported by this tool.
