### ISSUE TITLE
iSerial of programmer gets corrupted after one attempt to write

### ISSUE THREAD

**Issue by adithyaselv** [vdudouyt/stm8flash#57]
Hi,
I have been trying to program multiple boards connected to single pc. I tried to use an additional argument iSerialNumber of the device to distinguish between multiple programmers. But when I run your flash code , the iserial number of the programmer seem to get corrupted after one attempt and I am unable to use that for the next time(I have to plug out the device and plug in again to get correct serial number). If I just try to open and close the usb port using libusb , the number doesn't get corrupted. Does your code access device config parameters somewhere ? or changes it somewhere while writing into STM flash ? Kindly help

**Comment by lkord** [comment]
@adithyaselv Can You tell how to use iSerial? Maybe some code example?

**Comment by adithyaselv** [comment]
wow great thanks
