### ISSUE TITLE
MacOSX Yosemite - error: use of undeclared identifier 'stderr'

### ISSUE THREAD

**Issue by e-onux** [vdudouyt/stm8flash#61]
make
cc -g -O0 --std=gnu99 --pedantic -I/usr/include/ -I/usr/include/sys -I/usr/include/machine -I/usr/local/Cellar/libusb/1.0.21/include/libusb-1.0    -c -o stlink.o stlink.c
stlink.c:250:3: warning: implicit declaration of function 'usleep' is invalid in
      C99 [-Wimplicit-function-declaration]
                usleep(10000);
                ^
stlink.c:345:4: warning: implicit declaration of function 'fprintf' is invalid
      in C99 [-Wimplicit-function-declaration]
                        fprintf(stderr, "Unknown status: %x\n", status);
                        ^
stlink.c:345:4: warning: declaration of built-in function 'fprintf' requires
      inclusion of the header <stdio.h> [-Wbuiltin-requires-header]
stlink.c:345:12: error: use of undeclared identifier 'stderr'
                        fprintf(stderr, "Unknown status: %x\n", status);
                                ^
stlink.c:545:12: error: use of undeclared identifier 'stderr'
                        fprintf(stderr, "Write error\n");
                                ^
3 warnings and 2 errors generated.
make: *** [stlink.o] Error 1

**Comment by e-onux** [comment]
xcode commandline tools already installed. But it throws error.

**Comment by KenjutsuGH** [comment]
I am having the same error on **macOS Sierra 10.12.5.**

**xcode-select --install** gives _xcode-select: error: command line tools are already installed, use "Software Update" to install updates_

**gcc -v** gives:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by spth** [comment]
I do see an #include <stdio.h> in the current stlink.c, so use of frpintf snd stderr shouldbe fine. Is this problem still there in the current version?

Philipp

**Comment by KenjutsuGH** [comment]
Yes, it is still a problem, even with `#include <stdio.h>`. I was able to resolve the problem and get it compiling, and working:

- Removed macOS SDK include directory dependency in `Makefile`
- Added `#ifndef `to remove inclusion of `endian.h` and `malloc.h` in `stlink.c` and `pgm.h`

It still compiles under Linux Mint 18.1, but I was not able to test it under Windows

**Comment by spth** [comment]
You fixes have been merged in July.

Philipp
