### ISSUE TITLE
Writing is slow

### ISSUE THREAD

**Issue by lujji** [vdudouyt/stm8flash#72]
Older commit:
```
$ time stm8flash -c stlinkv2 -p stm8s003f3 -w empty.bin 
Determine FLASH area
Writing binary file 6144 bytes at 0x8000... OK
Bytes written: 6144

real    0m2.735s
user    0m0.020s
sys     0m0.000s
```

Master:
```
$ time stm8flash -c stlinkv2 -p stm8s003f3 -w empty.bin 
Determine FLASH area
Writing binary file 6144 bytes at 0x8000... OK
Bytes written: 6144

real    0m4.124s
user    0m0.000s
sys     0m0.020s
```

The issue seems to be introduced in [b8dcaa1](https://github.com/vdudouyt/stm8flash/commit/b8dcaa1c73347c393137cc7bba8e155ee5297a36). Also, what is the purpose of `usleep(2000)` in `stlink2_write_` functions? Code uses blocking libusb transfers so I'm not exactly sure why this delay is needed.

**Comment by spth** [comment]
There is work-in-progress on an stlinkv2 driver rewrite (https://github.com/vdudouyt/stm8flash/pull/144) that enables SWIM high-speed mode. For me, it results in an about 8x speedup.
