### ISSUE TITLE
make show error

### ISSUE THREAD

**Issue by Rombersoft** [vdudouyt/stm8flash#99]
```
cc -g -O0 --std=gnu99 --pedantic `pkg-config --cflags libusb-1.0`    -c -o stlink.o stlink.c
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
In file included from stlink.c:17:0:
pgm.h:7:21: fatal error: libusb.h: Немає такого файла або каталогу
compilation terminated.
<вбудований>: спроба виконання рецепта для мети «stlink.o» зазнала невдачі
make: *** [stlink.o] Помилка 1

```
but libusb-1.0 really exists

**Comment by vdudouyt** [comment]
It looks that you don't have libusb-1.0 development headers installed.

**Comment by microwiz** [comment]
In Ubuntu 16.04.4 LTS, I was able to get past this error by installing libusb. I used "sudo apt-get install libusb-1.0" and all was taken care by apt.

This issue can be closed.

**Comment by vksingh18881** [comment]
In Ubuntu 18.04.2 LTS I have same problem as mentioned by Rombersoft. I have installed installed libusb-1.0-0-dev but error remains the same. libusb.h is in /usr/include/libusb-1.0/
Please kindly help.

**Comment by Picatout** [comment]
@vksingh18881,  
I had the same problem in ubuntu 18.04.3 LTS I installed pkg-config and issue was solved.
sudo apt install pkg-config
